### ISSUE TITLE
Midterm-if is ready to be graded

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#10]
I did come up with 2425. I couldn't figure out how to use the loop so it auto calculated the lines. I believe we were supposed to use the while loop again and have that auto calculate as we added another keyword. i am going to have to go back to the loop section again. Thanks again for letting me turn this in after midnight.

Nick Wanless

**Comment by cethenmc** [comment]
Neatly done.  All concepts you used were concepts learned in class, which was nice to see.  I want to overlook some minor things, but I cannot.  You imported fabs but were not using the module, and you printed out  the incremental sums.  (1 pt).  The requirements should have only printed your name line and your total line.   I assume you could not recall a method to extract the line number as requested.  What if the lines had gaps in IDs, weren't sorted, or their IDs started with 1000?  Move Lanie Whiteland's record down between IDs 13 and 14, and your total would end up being 2427.  Extracting the line number (2 pts) and converting it to an int (2 pts) [which was a hint to help you know what you might use to extract] were two required steps.  Finally, you ended up keeping a counter for your line number, but the print at the end was a non-dynamic, hard-coded value of 2425 (since you went through the work of counting, you should have stored those counts for your search criteria so it could have been dynamic (2 pts).  Your score for this part is 26/33.
