### ISSUE TITLE
Week 10 - Subprocesses assignment is ready for Grading

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#13]
I think this one went well.

**Comment by cethenmc** [comment]
Fairly well, but got messed up in the for loop and getting the length.  6 for 8 now but you can still get full credit.

When printing you can keep the title COMMAND at the top.
When counting the length you should not count COMMAND at the top.
Since you are in there, be sure to add the #Author: at the top between the shebang and the description comment.

You have the two things reversed.

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208687005-881f8e61-b8f8-4cf4-b6f1-9c3ee1e51c74.png)
