### ISSUE TITLE
Week 12 Sockets (4) are complete.

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#15]
I understand the concepts of sockets. I think i am missing some pieces though. I am going to hopefully get Week 13-14 done over Thanksgiving break and then hopefully find time to chat with you over some questions. I will look at your schedule for next week and reach out to you about getting some time scheduled before the Final. Thank you.

Nick Wanless

**Comment by cethenmc** [comment]
Hi, Nick.  I have not seen that you have reached out yet, and you mentioned ten days ago you would try.  I am happy to help.  If you have attempted to book through Instructor Contact on Blackboard and those times do not work for you, please don't hesitate to reach out via email with some general times that would work better for you.  I will marry up your times with my schedule to see if we can find one that works for both.

Regarding this Week 12 lab:

Chat Scripts:
1. chat-server.py - Full 2 points earned
2. chat-client.py - It's not chatting.  You have some pieces, rounding up to 1 out of 2 points earned. You just need to (1) set **SND_DATA = ""** at the top instead of "This is Nick's TEST", (2) add the line to loop **while SND_DATA != 'exit'**, (3) indent the current lines 15, 16, and 18 under it, and (4) just above those three indented insert a line to accept user input **SND_DATA = input(">>>>")**

Filetransfer Scripts:  3 of 4 points earned...
In filetransfer-server.py, please change TransmitFile.txt to TransmitFile2.txt or some other filename to accomplishe what you set out to do.  You opted not to use the industry standard that we suggested (LHOST, LPORT, RHOST, RPORT, SND_DATA, RCV_DATA, C_SOCK, etc., in either of the file transfer scripts).  

I like the fact that you picked up on using 'b' in your reading and writing!

Grading as 6 out of 8 for now, but please feel free to clean up these things and reply to this issue when corrected, if you would like full credit.  Otherwise, reply to this ticket if you'd like to keep the 6 out of 8, and I will close the issue ticket.

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208687005-881f8e61-b8f8-4cf4-b6f1-9c3ee1e51c74.png)
