### ISSUE TITLE
Week14 my-json.py. Finished

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#17]
I can't for the life of me figure out how to add the argparse piece so i can call a specific IP for the json file to search for. If i add my IP address to the URL. I get the correct output in my file. IF i leave the IP address out of the URL and try to add it using various argparse techniques it defaults to a local IP address every time. Not sure exactly what i am missing here. Thanks.

Nick

**Comment by cethenmc** [comment]
Set up some time and we can walk through it together.  I should have mentioned also, that you are more than welcome to attend my labs Tu/Th 12:30 - 2:10 PM if they are convenient for you.  Otherwise, book me through Instructor Contact on Blackboard.  If none of those times work out, please do not hesitate to email with different times that would work for you, and I will try to find those holes in my schedule.

**For now, 4 out of 8.  Repush the corrected code to GitHub and reply to this Issue Ticket to attempt to receive full credit.**

- Your struggle started from line 10, as you set up the parser wrong.  You forgot the keyword description= and should offer more of a description than just 'ip'.
- Line 11 should have a long flag of --ipaddress (not just --ip) to follow the requirements, and you have no dest= to capture the argument (e.g., dest=ipAddr).
- Line 12 you did not use parse_args() -- yes, I know line 12 is blank.  You omitted this key step.
- Line 14 you know you hardcoded the IP as you mentioned above, but you also changed it to SSL and left off /json.  Instead try this (after you make your variable on Line 12 above arguments) "http://ipinfo.io" + arguments.ipAddr +"/json"

**Comment by nwanless-matc** [comment]
I figured this out with your help from above and resubmitted this. Thank you.

**Comment by cethenmc** [comment]
Grade switched to an 8 out of 8.  Thank you for resubmitting.
