### ISSUE TITLE
Midterm: JPark and Strings are ready to be graded.

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#9]
I am going to get midterm-if done asap. These ended up taking me longer than expected. I thought most of the weekly assignments were straight forward. i didn't expect the midterm to go like this. I have issues on both these files, and i was hoping they would be perfect.

Jpark- I added my while loop towards the end with counter < 3 to continue trying. It got stuck in a loop at the login, so i ended up removing it. My other issue is that my username and login is always wrong. i set up dictionary and if statements, but not sure what is wrong there.

Slicing - I ran out of time in figuring out how to strip my results. For the lines i had more than one word I still have the quotes and "\n". This may be where i was supposed to use the replace command to clean them up. i thought strip would work, but it is either wrong or i was using it wrong.

Thanks.

Nick

**Comment by cethenmc** [comment]
The third part of the Midterm was Slicing (not Strings).  
**Midterm-jpark:**  There were not three tries allowed for logging in.  The user receives the right text, but it ends the program before allowing two more tries.  White_rabit was never used after instantiation  (6 pts).  The comparison on line 32 was programmed incorrectly, but it was a nice idea to try to use the values (2 pts).  In line 36, keys were to be extracted from the command_database dictionary (2 pts).  Lines 40-45 could have been done more easily using the input to look up received to find the value. I will take less off because I believe your actions were to demonstrate your understanding of 3.iv.  However that could be simplified since three of the things do the same thing [meaning pull its value from the dictionary] (2 pts).  Your score for this part is 21/33
**Midterm-slicing:**  Thanks for effort in attempting to put together the quote neatly.  I appreciate that your code is clean, so I can see what areas you struggled with.  Var3 and var5 you struggled to get a single slice, and did three for each of them (4 pts).  The extra prints were not required, you were asked to print only your name and the final quote as output (2 pts).  Because you picked up individual words in var3 and var5, you almost would have been better served to keep them all as strings instead of making tuples.  Either way you could have brought them all together with a join (2 pts), and then replaced out the new line feeds [\n] (2 pts).  24/34
